### ISSUE TITLE
better error message upon malformed JSON

### ISSUE THREAD

**Issue by esaule** [squeetus/bridgesAPI#31]
Right now it seems that when the server receives a malformed JSON it dies with 500 internal server error. Would it be hard to get a slightly more verbose error code (not sure what exactly) to hint to the client that the JSON is malformed?
If it is hard no worries, but it is is easy, that would be a good help when debugging.

**Comment by squeetus** [comment]
Which endpoints are you hitting, assignment uploading?

**Comment by esaule** [comment]
That is the one I was thinking of. But in general, get 500 Internal
Server error when the problem is "the post request does not make
sense" is not best.

**Comment by squeetus** [comment]
So this is primarily for uploading assignments? Is this happening from a particular client language or all?

**Comment by squeetus** [comment]
I can configure the generic default error message to return 404 instead of 500, but I do not know the effect that will have on the client APIs (are they configured to look for 500, or just >200 status codes?)

Or I can modify the assignment upload method specifically to return 404 when JSON parsing fails.

**Comment by esaule** [comment]
Shouldn't that be a 400 return code then ? (see: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes )

**Comment by squeetus** [comment]
Either one is trivial to add. 

If the latter option, then yes I think 400 makes the most sense since it is malformed JSON.  

If the former option, 404 may be better as a generic catch-all.

**Comment by esaule** [comment]
If JSON parsing fails, we should return 400, I believe. This post ( https://softwareengineering.stackexchange.com/questions/329229/should-i-return-an-http-400-bad-request-status-if-a-parameter-is-syntactically ) seems to confirm that 400 is the right code.

**Comment by esaule** [comment]
404 is really "not found" which ain't quite the problem here.

**Comment by squeetus** [comment]
I think there are two separate questions at work here:

(1) should we return 400 in the specific case where someone posts a JSON object for an assignment and the JSON is not parseable? **probably yes**.

(2) should we modify the main catch-all error handling middleware to return 404(resource not found - or something else) instead of 500 (internal server error)? **maybe** (see my point about clients looking for 500 explicitly or looking for >200 status codes to determine errors). 

At the moment, Java and Python versions post JSON strings whereas C++ seems to post JSON objects. Multiple stages of the assignment upload process can fail, so we have a generic catch-all error handling middleware to avoid having a bunch of different hard-coded errors thrown. This currently throws 500. I can override any particular error with something more explicit wherever that's useful.

**Comment by squeetus** [comment]
Commit https://github.com/squeetus/bridgesAPI/commit/cc16bba0bb53055ad015532312aa643512617972
adds a few specific response codes for the assignments api. 

Default error handling middleware still returns 500 if nothing more explicit is thrown. 

I'm closing this for now. If you find other endpoints that need better response codes please make another issue and I can update those too.

**Comment by esaule** [comment]
I think 500 for a catch all is fine.
I don't think any of the clients do parse the error back carefully. We probably should at some point do just that. But at least with a more precise code, manual debugging should get easier (because the error code is printed with the message from the server.)
